# This is the config file for the UNewHaven Amateur Radio Club

title: UNewHaven Amateur Radio Club
email: amateur_radio@newhaven.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the webpage for the University of New Haven's Amateur Radio Club
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://unewhaven-amateur-radio-club.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "unewhaven-amateur-radio-club.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minimal-mistakes-jekyll
# For GitHub pages
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache

atom_feed:
  hide: true

include: ["_pages"]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
